//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Vigilant.Entities", "FK_Receptor_Endpoint", "Endpoint", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Vigilant.Entities.Endpoint), "Receptor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Vigilant.Entities.Receptor), true)]
[assembly: EdmRelationshipAttribute("Vigilant.Entities", "FK_Failure_Response", "Response", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Vigilant.Entities.Response), "Failure", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Vigilant.Entities.Failure), true)]
[assembly: EdmRelationshipAttribute("Vigilant.Entities", "FK_Receptor_UrlCheck", "UrlCheck", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Vigilant.Entities.UrlCheck), "Receptor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Vigilant.Entities.Receptor), true)]
[assembly: EdmRelationshipAttribute("Vigilant.Entities", "FK_Response_Receptor", "Receptor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Vigilant.Entities.Receptor), "Response", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Vigilant.Entities.Response), true)]
[assembly: EdmRelationshipAttribute("Vigilant.Entities", "AlertGroup_Receptor", "AlertGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Vigilant.Entities.AlertGroup), "Receptor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Vigilant.Entities.Receptor))]
[assembly: EdmRelationshipAttribute("Vigilant.Entities", "AlertGroup_RecipientGroup", "AlertGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Vigilant.Entities.AlertGroup), "RecipientGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Vigilant.Entities.RecipientGroup))]
[assembly: EdmRelationshipAttribute("Vigilant.Entities", "RecipientGroup_EmailRecipient", "EmailRecipient", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Vigilant.Entities.EmailRecipient), "RecipientGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Vigilant.Entities.RecipientGroup))]
[assembly: EdmRelationshipAttribute("Vigilant.Entities", "RecipientGroup_SmsRecipient", "RecipientGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Vigilant.Entities.RecipientGroup), "SmsRecipient", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Vigilant.Entities.SmsRecipient))]

#endregion

namespace Vigilant.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class VigilantDatabase : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new VigilantDatabase object using the connection string found in the 'VigilantDatabase' section of the application configuration file.
        /// </summary>
        public VigilantDatabase() : base("name=VigilantDatabase", "VigilantDatabase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VigilantDatabase object.
        /// </summary>
        public VigilantDatabase(string connectionString) : base(connectionString, "VigilantDatabase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VigilantDatabase object.
        /// </summary>
        public VigilantDatabase(EntityConnection connection) : base(connection, "VigilantDatabase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AlertGroup> AlertGroups
        {
            get
            {
                if ((_AlertGroups == null))
                {
                    _AlertGroups = base.CreateObjectSet<AlertGroup>("AlertGroups");
                }
                return _AlertGroups;
            }
        }
        private ObjectSet<AlertGroup> _AlertGroups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EmailRecipient> EmailRecipients
        {
            get
            {
                if ((_EmailRecipients == null))
                {
                    _EmailRecipients = base.CreateObjectSet<EmailRecipient>("EmailRecipients");
                }
                return _EmailRecipients;
            }
        }
        private ObjectSet<EmailRecipient> _EmailRecipients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Endpoint> Endpoints
        {
            get
            {
                if ((_Endpoints == null))
                {
                    _Endpoints = base.CreateObjectSet<Endpoint>("Endpoints");
                }
                return _Endpoints;
            }
        }
        private ObjectSet<Endpoint> _Endpoints;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Failure> Failures
        {
            get
            {
                if ((_Failures == null))
                {
                    _Failures = base.CreateObjectSet<Failure>("Failures");
                }
                return _Failures;
            }
        }
        private ObjectSet<Failure> _Failures;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Receptor> Receptors
        {
            get
            {
                if ((_Receptors == null))
                {
                    _Receptors = base.CreateObjectSet<Receptor>("Receptors");
                }
                return _Receptors;
            }
        }
        private ObjectSet<Receptor> _Receptors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RecipientGroup> RecipientGroups
        {
            get
            {
                if ((_RecipientGroups == null))
                {
                    _RecipientGroups = base.CreateObjectSet<RecipientGroup>("RecipientGroups");
                }
                return _RecipientGroups;
            }
        }
        private ObjectSet<RecipientGroup> _RecipientGroups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Response> Responses
        {
            get
            {
                if ((_Responses == null))
                {
                    _Responses = base.CreateObjectSet<Response>("Responses");
                }
                return _Responses;
            }
        }
        private ObjectSet<Response> _Responses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SmsRecipient> SmsRecipients
        {
            get
            {
                if ((_SmsRecipients == null))
                {
                    _SmsRecipients = base.CreateObjectSet<SmsRecipient>("SmsRecipients");
                }
                return _SmsRecipients;
            }
        }
        private ObjectSet<SmsRecipient> _SmsRecipients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UrlCheck> UrlChecks
        {
            get
            {
                if ((_UrlChecks == null))
                {
                    _UrlChecks = base.CreateObjectSet<UrlCheck>("UrlChecks");
                }
                return _UrlChecks;
            }
        }
        private ObjectSet<UrlCheck> _UrlChecks;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AlertGroups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAlertGroups(AlertGroup alertGroup)
        {
            base.AddObject("AlertGroups", alertGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EmailRecipients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmailRecipients(EmailRecipient emailRecipient)
        {
            base.AddObject("EmailRecipients", emailRecipient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Endpoints EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEndpoints(Endpoint endpoint)
        {
            base.AddObject("Endpoints", endpoint);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Failures EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFailures(Failure failure)
        {
            base.AddObject("Failures", failure);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Receptors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReceptors(Receptor receptor)
        {
            base.AddObject("Receptors", receptor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RecipientGroups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecipientGroups(RecipientGroup recipientGroup)
        {
            base.AddObject("RecipientGroups", recipientGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Responses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToResponses(Response response)
        {
            base.AddObject("Responses", response);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SmsRecipients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSmsRecipients(SmsRecipient smsRecipient)
        {
            base.AddObject("SmsRecipients", smsRecipient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UrlChecks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUrlChecks(UrlCheck urlCheck)
        {
            base.AddObject("UrlChecks", urlCheck);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Vigilant.Entities", Name="AlertGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AlertGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AlertGroup object.
        /// </summary>
        /// <param name="alertGroupId">Initial value of the AlertGroupId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static AlertGroup CreateAlertGroup(global::System.Int32 alertGroupId, global::System.String name)
        {
            AlertGroup alertGroup = new AlertGroup();
            alertGroup.AlertGroupId = alertGroupId;
            alertGroup.Name = name;
            return alertGroup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AlertGroupId
        {
            get
            {
                return _AlertGroupId;
            }
            set
            {
                if (_AlertGroupId != value)
                {
                    OnAlertGroupIdChanging(value);
                    ReportPropertyChanging("AlertGroupId");
                    _AlertGroupId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AlertGroupId");
                    OnAlertGroupIdChanged();
                }
            }
        }
        private global::System.Int32 _AlertGroupId;
        partial void OnAlertGroupIdChanging(global::System.Int32 value);
        partial void OnAlertGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Vigilant.Entities", "AlertGroup_Receptor", "Receptor")]
        public EntityCollection<Receptor> Receptors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Receptor>("Vigilant.Entities.AlertGroup_Receptor", "Receptor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Receptor>("Vigilant.Entities.AlertGroup_Receptor", "Receptor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Vigilant.Entities", "AlertGroup_RecipientGroup", "RecipientGroup")]
        public EntityCollection<RecipientGroup> RecipientGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecipientGroup>("Vigilant.Entities.AlertGroup_RecipientGroup", "RecipientGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecipientGroup>("Vigilant.Entities.AlertGroup_RecipientGroup", "RecipientGroup", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Vigilant.Entities", Name="EmailRecipient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EmailRecipient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EmailRecipient object.
        /// </summary>
        /// <param name="emailRecipientId">Initial value of the EmailRecipientId property.</param>
        public static EmailRecipient CreateEmailRecipient(global::System.Int32 emailRecipientId)
        {
            EmailRecipient emailRecipient = new EmailRecipient();
            emailRecipient.EmailRecipientId = emailRecipientId;
            return emailRecipient;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmailRecipientId
        {
            get
            {
                return _EmailRecipientId;
            }
            set
            {
                if (_EmailRecipientId != value)
                {
                    OnEmailRecipientIdChanging(value);
                    ReportPropertyChanging("EmailRecipientId");
                    _EmailRecipientId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EmailRecipientId");
                    OnEmailRecipientIdChanged();
                }
            }
        }
        private global::System.Int32 _EmailRecipientId;
        partial void OnEmailRecipientIdChanging(global::System.Int32 value);
        partial void OnEmailRecipientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Vigilant.Entities", "RecipientGroup_EmailRecipient", "RecipientGroup")]
        public EntityCollection<RecipientGroup> RecipientGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecipientGroup>("Vigilant.Entities.RecipientGroup_EmailRecipient", "RecipientGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecipientGroup>("Vigilant.Entities.RecipientGroup_EmailRecipient", "RecipientGroup", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Vigilant.Entities", Name="Endpoint")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Endpoint : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Endpoint object.
        /// </summary>
        /// <param name="endpointId">Initial value of the EndpointId property.</param>
        /// <param name="nickname">Initial value of the Nickname property.</param>
        /// <param name="ipAddress">Initial value of the IpAddress property.</param>
        public static Endpoint CreateEndpoint(global::System.Int32 endpointId, global::System.String nickname, global::System.String ipAddress)
        {
            Endpoint endpoint = new Endpoint();
            endpoint.EndpointId = endpointId;
            endpoint.Nickname = nickname;
            endpoint.IpAddress = ipAddress;
            return endpoint;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EndpointId
        {
            get
            {
                return _EndpointId;
            }
            set
            {
                if (_EndpointId != value)
                {
                    OnEndpointIdChanging(value);
                    ReportPropertyChanging("EndpointId");
                    _EndpointId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EndpointId");
                    OnEndpointIdChanged();
                }
            }
        }
        private global::System.Int32 _EndpointId;
        partial void OnEndpointIdChanging(global::System.Int32 value);
        partial void OnEndpointIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nickname
        {
            get
            {
                return _Nickname;
            }
            set
            {
                OnNicknameChanging(value);
                ReportPropertyChanging("Nickname");
                _Nickname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nickname");
                OnNicknameChanged();
            }
        }
        private global::System.String _Nickname;
        partial void OnNicknameChanging(global::System.String value);
        partial void OnNicknameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IpAddress
        {
            get
            {
                return _IpAddress;
            }
            set
            {
                OnIpAddressChanging(value);
                ReportPropertyChanging("IpAddress");
                _IpAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IpAddress");
                OnIpAddressChanged();
            }
        }
        private global::System.String _IpAddress;
        partial void OnIpAddressChanging(global::System.String value);
        partial void OnIpAddressChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Vigilant.Entities", "FK_Receptor_Endpoint", "Receptor")]
        public EntityCollection<Receptor> Receptors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Receptor>("Vigilant.Entities.FK_Receptor_Endpoint", "Receptor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Receptor>("Vigilant.Entities.FK_Receptor_Endpoint", "Receptor", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Vigilant.Entities", Name="Failure")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Failure : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Failure object.
        /// </summary>
        /// <param name="responseId">Initial value of the ResponseId property.</param>
        /// <param name="exceptionMessage">Initial value of the ExceptionMessage property.</param>
        public static Failure CreateFailure(global::System.Int32 responseId, global::System.String exceptionMessage)
        {
            Failure failure = new Failure();
            failure.ResponseId = responseId;
            failure.ExceptionMessage = exceptionMessage;
            return failure;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ResponseId
        {
            get
            {
                return _ResponseId;
            }
            set
            {
                if (_ResponseId != value)
                {
                    OnResponseIdChanging(value);
                    ReportPropertyChanging("ResponseId");
                    _ResponseId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ResponseId");
                    OnResponseIdChanged();
                }
            }
        }
        private global::System.Int32 _ResponseId;
        partial void OnResponseIdChanging(global::System.Int32 value);
        partial void OnResponseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ExceptionMessage
        {
            get
            {
                return _ExceptionMessage;
            }
            set
            {
                OnExceptionMessageChanging(value);
                ReportPropertyChanging("ExceptionMessage");
                _ExceptionMessage = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ExceptionMessage");
                OnExceptionMessageChanged();
            }
        }
        private global::System.String _ExceptionMessage;
        partial void OnExceptionMessageChanging(global::System.String value);
        partial void OnExceptionMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StackTrace
        {
            get
            {
                return _StackTrace;
            }
            set
            {
                OnStackTraceChanging(value);
                ReportPropertyChanging("StackTrace");
                _StackTrace = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StackTrace");
                OnStackTraceChanged();
            }
        }
        private global::System.String _StackTrace;
        partial void OnStackTraceChanging(global::System.String value);
        partial void OnStackTraceChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Vigilant.Entities", "FK_Failure_Response", "Response")]
        public Response Response
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Response>("Vigilant.Entities.FK_Failure_Response", "Response").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Response>("Vigilant.Entities.FK_Failure_Response", "Response").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Response> ResponseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Response>("Vigilant.Entities.FK_Failure_Response", "Response");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Response>("Vigilant.Entities.FK_Failure_Response", "Response", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Vigilant.Entities", Name="Receptor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Receptor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Receptor object.
        /// </summary>
        /// <param name="receptorId">Initial value of the ReceptorId property.</param>
        /// <param name="urlCheckId">Initial value of the UrlCheckId property.</param>
        /// <param name="endpointId">Initial value of the EndpointId property.</param>
        /// <param name="frequency">Initial value of the Frequency property.</param>
        public static Receptor CreateReceptor(global::System.Int32 receptorId, global::System.Int32 urlCheckId, global::System.Int32 endpointId, global::System.TimeSpan frequency)
        {
            Receptor receptor = new Receptor();
            receptor.ReceptorId = receptorId;
            receptor.UrlCheckId = urlCheckId;
            receptor.EndpointId = endpointId;
            receptor.Frequency = frequency;
            return receptor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReceptorId
        {
            get
            {
                return _ReceptorId;
            }
            set
            {
                if (_ReceptorId != value)
                {
                    OnReceptorIdChanging(value);
                    ReportPropertyChanging("ReceptorId");
                    _ReceptorId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ReceptorId");
                    OnReceptorIdChanged();
                }
            }
        }
        private global::System.Int32 _ReceptorId;
        partial void OnReceptorIdChanging(global::System.Int32 value);
        partial void OnReceptorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UrlCheckId
        {
            get
            {
                return _UrlCheckId;
            }
            set
            {
                OnUrlCheckIdChanging(value);
                ReportPropertyChanging("UrlCheckId");
                _UrlCheckId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UrlCheckId");
                OnUrlCheckIdChanged();
            }
        }
        private global::System.Int32 _UrlCheckId;
        partial void OnUrlCheckIdChanging(global::System.Int32 value);
        partial void OnUrlCheckIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EndpointId
        {
            get
            {
                return _EndpointId;
            }
            set
            {
                OnEndpointIdChanging(value);
                ReportPropertyChanging("EndpointId");
                _EndpointId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndpointId");
                OnEndpointIdChanged();
            }
        }
        private global::System.Int32 _EndpointId;
        partial void OnEndpointIdChanging(global::System.Int32 value);
        partial void OnEndpointIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan Frequency
        {
            get
            {
                return _Frequency;
            }
            set
            {
                OnFrequencyChanging(value);
                ReportPropertyChanging("Frequency");
                _Frequency = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Frequency");
                OnFrequencyChanged();
            }
        }
        private global::System.TimeSpan _Frequency;
        partial void OnFrequencyChanging(global::System.TimeSpan value);
        partial void OnFrequencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastTestedAtUtc
        {
            get
            {
                return _LastTestedAtUtc;
            }
            set
            {
                OnLastTestedAtUtcChanging(value);
                ReportPropertyChanging("LastTestedAtUtc");
                _LastTestedAtUtc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastTestedAtUtc");
                OnLastTestedAtUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastTestedAtUtc;
        partial void OnLastTestedAtUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnLastTestedAtUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> LastCheckWasUnstable
        {
            get
            {
                return _LastCheckWasUnstable;
            }
            set
            {
                OnLastCheckWasUnstableChanging(value);
                ReportPropertyChanging("LastCheckWasUnstable");
                _LastCheckWasUnstable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastCheckWasUnstable");
                OnLastCheckWasUnstableChanged();
            }
        }
        private Nullable<global::System.Boolean> _LastCheckWasUnstable;
        partial void OnLastCheckWasUnstableChanging(Nullable<global::System.Boolean> value);
        partial void OnLastCheckWasUnstableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> LastCheckWasCritical
        {
            get
            {
                return _LastCheckWasCritical;
            }
            set
            {
                OnLastCheckWasCriticalChanging(value);
                ReportPropertyChanging("LastCheckWasCritical");
                _LastCheckWasCritical = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastCheckWasCritical");
                OnLastCheckWasCriticalChanged();
            }
        }
        private Nullable<global::System.Boolean> _LastCheckWasCritical;
        partial void OnLastCheckWasCriticalChanging(Nullable<global::System.Boolean> value);
        partial void OnLastCheckWasCriticalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LastResponseTimeInMilliseconds
        {
            get
            {
                return _LastResponseTimeInMilliseconds;
            }
            set
            {
                OnLastResponseTimeInMillisecondsChanging(value);
                ReportPropertyChanging("LastResponseTimeInMilliseconds");
                _LastResponseTimeInMilliseconds = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastResponseTimeInMilliseconds");
                OnLastResponseTimeInMillisecondsChanged();
            }
        }
        private Nullable<global::System.Int32> _LastResponseTimeInMilliseconds;
        partial void OnLastResponseTimeInMillisecondsChanging(Nullable<global::System.Int32> value);
        partial void OnLastResponseTimeInMillisecondsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Vigilant.Entities", "FK_Receptor_Endpoint", "Endpoint")]
        public Endpoint Endpoint
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Endpoint>("Vigilant.Entities.FK_Receptor_Endpoint", "Endpoint").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Endpoint>("Vigilant.Entities.FK_Receptor_Endpoint", "Endpoint").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Endpoint> EndpointReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Endpoint>("Vigilant.Entities.FK_Receptor_Endpoint", "Endpoint");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Endpoint>("Vigilant.Entities.FK_Receptor_Endpoint", "Endpoint", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Vigilant.Entities", "FK_Receptor_UrlCheck", "UrlCheck")]
        public UrlCheck UrlCheck
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UrlCheck>("Vigilant.Entities.FK_Receptor_UrlCheck", "UrlCheck").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UrlCheck>("Vigilant.Entities.FK_Receptor_UrlCheck", "UrlCheck").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UrlCheck> UrlCheckReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UrlCheck>("Vigilant.Entities.FK_Receptor_UrlCheck", "UrlCheck");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UrlCheck>("Vigilant.Entities.FK_Receptor_UrlCheck", "UrlCheck", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Vigilant.Entities", "FK_Response_Receptor", "Response")]
        public EntityCollection<Response> Responses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Response>("Vigilant.Entities.FK_Response_Receptor", "Response");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Response>("Vigilant.Entities.FK_Response_Receptor", "Response", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Vigilant.Entities", "AlertGroup_Receptor", "AlertGroup")]
        public EntityCollection<AlertGroup> AlertGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AlertGroup>("Vigilant.Entities.AlertGroup_Receptor", "AlertGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AlertGroup>("Vigilant.Entities.AlertGroup_Receptor", "AlertGroup", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Vigilant.Entities", Name="RecipientGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RecipientGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RecipientGroup object.
        /// </summary>
        /// <param name="recipientGroupId">Initial value of the RecipientGroupId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static RecipientGroup CreateRecipientGroup(global::System.Int32 recipientGroupId, global::System.String name)
        {
            RecipientGroup recipientGroup = new RecipientGroup();
            recipientGroup.RecipientGroupId = recipientGroupId;
            recipientGroup.Name = name;
            return recipientGroup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipientGroupId
        {
            get
            {
                return _RecipientGroupId;
            }
            set
            {
                if (_RecipientGroupId != value)
                {
                    OnRecipientGroupIdChanging(value);
                    ReportPropertyChanging("RecipientGroupId");
                    _RecipientGroupId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RecipientGroupId");
                    OnRecipientGroupIdChanged();
                }
            }
        }
        private global::System.Int32 _RecipientGroupId;
        partial void OnRecipientGroupIdChanging(global::System.Int32 value);
        partial void OnRecipientGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Vigilant.Entities", "AlertGroup_RecipientGroup", "AlertGroup")]
        public EntityCollection<AlertGroup> AlertGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AlertGroup>("Vigilant.Entities.AlertGroup_RecipientGroup", "AlertGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AlertGroup>("Vigilant.Entities.AlertGroup_RecipientGroup", "AlertGroup", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Vigilant.Entities", "RecipientGroup_EmailRecipient", "EmailRecipient")]
        public EntityCollection<EmailRecipient> EmailRecipients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EmailRecipient>("Vigilant.Entities.RecipientGroup_EmailRecipient", "EmailRecipient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EmailRecipient>("Vigilant.Entities.RecipientGroup_EmailRecipient", "EmailRecipient", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Vigilant.Entities", "RecipientGroup_SmsRecipient", "SmsRecipient")]
        public EntityCollection<SmsRecipient> SmsRecipients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SmsRecipient>("Vigilant.Entities.RecipientGroup_SmsRecipient", "SmsRecipient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SmsRecipient>("Vigilant.Entities.RecipientGroup_SmsRecipient", "SmsRecipient", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Vigilant.Entities", Name="Response")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Response : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Response object.
        /// </summary>
        /// <param name="responseId">Initial value of the ResponseId property.</param>
        /// <param name="receptorId">Initial value of the ReceptorId property.</param>
        /// <param name="requestSentAtUtc">Initial value of the RequestSentAtUtc property.</param>
        /// <param name="isUnstable">Initial value of the IsUnstable property.</param>
        /// <param name="isCritical">Initial value of the IsCritical property.</param>
        public static Response CreateResponse(global::System.Int32 responseId, global::System.Int32 receptorId, global::System.DateTime requestSentAtUtc, global::System.Boolean isUnstable, global::System.Boolean isCritical)
        {
            Response response = new Response();
            response.ResponseId = responseId;
            response.ReceptorId = receptorId;
            response.RequestSentAtUtc = requestSentAtUtc;
            response.IsUnstable = isUnstable;
            response.IsCritical = isCritical;
            return response;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ResponseId
        {
            get
            {
                return _ResponseId;
            }
            set
            {
                if (_ResponseId != value)
                {
                    OnResponseIdChanging(value);
                    ReportPropertyChanging("ResponseId");
                    _ResponseId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ResponseId");
                    OnResponseIdChanged();
                }
            }
        }
        private global::System.Int32 _ResponseId;
        partial void OnResponseIdChanging(global::System.Int32 value);
        partial void OnResponseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReceptorId
        {
            get
            {
                return _ReceptorId;
            }
            set
            {
                OnReceptorIdChanging(value);
                ReportPropertyChanging("ReceptorId");
                _ReceptorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReceptorId");
                OnReceptorIdChanged();
            }
        }
        private global::System.Int32 _ReceptorId;
        partial void OnReceptorIdChanging(global::System.Int32 value);
        partial void OnReceptorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RequestSentAtUtc
        {
            get
            {
                return _RequestSentAtUtc;
            }
            set
            {
                OnRequestSentAtUtcChanging(value);
                ReportPropertyChanging("RequestSentAtUtc");
                _RequestSentAtUtc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RequestSentAtUtc");
                OnRequestSentAtUtcChanged();
            }
        }
        private global::System.DateTime _RequestSentAtUtc;
        partial void OnRequestSentAtUtcChanging(global::System.DateTime value);
        partial void OnRequestSentAtUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsUnstable
        {
            get
            {
                return _IsUnstable;
            }
            set
            {
                OnIsUnstableChanging(value);
                ReportPropertyChanging("IsUnstable");
                _IsUnstable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsUnstable");
                OnIsUnstableChanged();
            }
        }
        private global::System.Boolean _IsUnstable;
        partial void OnIsUnstableChanging(global::System.Boolean value);
        partial void OnIsUnstableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsCritical
        {
            get
            {
                return _IsCritical;
            }
            set
            {
                OnIsCriticalChanging(value);
                ReportPropertyChanging("IsCritical");
                _IsCritical = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsCritical");
                OnIsCriticalChanged();
            }
        }
        private global::System.Boolean _IsCritical;
        partial void OnIsCriticalChanging(global::System.Boolean value);
        partial void OnIsCriticalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ResponseTimeInMilliseconds
        {
            get
            {
                return _ResponseTimeInMilliseconds;
            }
            set
            {
                OnResponseTimeInMillisecondsChanging(value);
                ReportPropertyChanging("ResponseTimeInMilliseconds");
                _ResponseTimeInMilliseconds = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ResponseTimeInMilliseconds");
                OnResponseTimeInMillisecondsChanged();
            }
        }
        private Nullable<global::System.Int32> _ResponseTimeInMilliseconds;
        partial void OnResponseTimeInMillisecondsChanging(Nullable<global::System.Int32> value);
        partial void OnResponseTimeInMillisecondsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Vigilant.Entities", "FK_Failure_Response", "Failure")]
        public Failure Failure
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Failure>("Vigilant.Entities.FK_Failure_Response", "Failure").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Failure>("Vigilant.Entities.FK_Failure_Response", "Failure").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Failure> FailureReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Failure>("Vigilant.Entities.FK_Failure_Response", "Failure");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Failure>("Vigilant.Entities.FK_Failure_Response", "Failure", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Vigilant.Entities", "FK_Response_Receptor", "Receptor")]
        public Receptor Receptor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Receptor>("Vigilant.Entities.FK_Response_Receptor", "Receptor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Receptor>("Vigilant.Entities.FK_Response_Receptor", "Receptor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Receptor> ReceptorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Receptor>("Vigilant.Entities.FK_Response_Receptor", "Receptor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Receptor>("Vigilant.Entities.FK_Response_Receptor", "Receptor", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Vigilant.Entities", Name="SmsRecipient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SmsRecipient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SmsRecipient object.
        /// </summary>
        /// <param name="smsRecipientId">Initial value of the SmsRecipientId property.</param>
        /// <param name="nickname">Initial value of the Nickname property.</param>
        /// <param name="mobileNumber">Initial value of the MobileNumber property.</param>
        /// <param name="noAlertsBefore">Initial value of the NoAlertsBefore property.</param>
        /// <param name="noAlertsAfter">Initial value of the NoAlertsAfter property.</param>
        public static SmsRecipient CreateSmsRecipient(global::System.Int32 smsRecipientId, global::System.String nickname, global::System.String mobileNumber, global::System.TimeSpan noAlertsBefore, global::System.TimeSpan noAlertsAfter)
        {
            SmsRecipient smsRecipient = new SmsRecipient();
            smsRecipient.SmsRecipientId = smsRecipientId;
            smsRecipient.Nickname = nickname;
            smsRecipient.MobileNumber = mobileNumber;
            smsRecipient.NoAlertsBefore = noAlertsBefore;
            smsRecipient.NoAlertsAfter = noAlertsAfter;
            return smsRecipient;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SmsRecipientId
        {
            get
            {
                return _SmsRecipientId;
            }
            set
            {
                if (_SmsRecipientId != value)
                {
                    OnSmsRecipientIdChanging(value);
                    ReportPropertyChanging("SmsRecipientId");
                    _SmsRecipientId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SmsRecipientId");
                    OnSmsRecipientIdChanged();
                }
            }
        }
        private global::System.Int32 _SmsRecipientId;
        partial void OnSmsRecipientIdChanging(global::System.Int32 value);
        partial void OnSmsRecipientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nickname
        {
            get
            {
                return _Nickname;
            }
            set
            {
                OnNicknameChanging(value);
                ReportPropertyChanging("Nickname");
                _Nickname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nickname");
                OnNicknameChanged();
            }
        }
        private global::System.String _Nickname;
        partial void OnNicknameChanging(global::System.String value);
        partial void OnNicknameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MobileNumber
        {
            get
            {
                return _MobileNumber;
            }
            set
            {
                OnMobileNumberChanging(value);
                ReportPropertyChanging("MobileNumber");
                _MobileNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MobileNumber");
                OnMobileNumberChanged();
            }
        }
        private global::System.String _MobileNumber;
        partial void OnMobileNumberChanging(global::System.String value);
        partial void OnMobileNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan NoAlertsBefore
        {
            get
            {
                return _NoAlertsBefore;
            }
            set
            {
                OnNoAlertsBeforeChanging(value);
                ReportPropertyChanging("NoAlertsBefore");
                _NoAlertsBefore = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NoAlertsBefore");
                OnNoAlertsBeforeChanged();
            }
        }
        private global::System.TimeSpan _NoAlertsBefore;
        partial void OnNoAlertsBeforeChanging(global::System.TimeSpan value);
        partial void OnNoAlertsBeforeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan NoAlertsAfter
        {
            get
            {
                return _NoAlertsAfter;
            }
            set
            {
                OnNoAlertsAfterChanging(value);
                ReportPropertyChanging("NoAlertsAfter");
                _NoAlertsAfter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NoAlertsAfter");
                OnNoAlertsAfterChanged();
            }
        }
        private global::System.TimeSpan _NoAlertsAfter;
        partial void OnNoAlertsAfterChanging(global::System.TimeSpan value);
        partial void OnNoAlertsAfterChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Vigilant.Entities", "RecipientGroup_SmsRecipient", "RecipientGroup")]
        public EntityCollection<RecipientGroup> RecipientGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecipientGroup>("Vigilant.Entities.RecipientGroup_SmsRecipient", "RecipientGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecipientGroup>("Vigilant.Entities.RecipientGroup_SmsRecipient", "RecipientGroup", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Vigilant.Entities", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Vigilant.Entities", Name="UrlCheck")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UrlCheck : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UrlCheck object.
        /// </summary>
        /// <param name="urlCheckId">Initial value of the UrlCheckId property.</param>
        /// <param name="useSsl">Initial value of the UseSsl property.</param>
        /// <param name="port">Initial value of the Port property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="rawHttpRequest">Initial value of the RawHttpRequest property.</param>
        /// <param name="expectedResponse">Initial value of the ExpectedResponse property.</param>
        /// <param name="unstableThresholdInMilliseconds">Initial value of the UnstableThresholdInMilliseconds property.</param>
        /// <param name="criticalThresholdInMilliseconds">Initial value of the CriticalThresholdInMilliseconds property.</param>
        public static UrlCheck CreateUrlCheck(global::System.Int32 urlCheckId, global::System.Boolean useSsl, global::System.Int32 port, global::System.String name, global::System.String rawHttpRequest, global::System.String expectedResponse, global::System.Int32 unstableThresholdInMilliseconds, global::System.Int32 criticalThresholdInMilliseconds)
        {
            UrlCheck urlCheck = new UrlCheck();
            urlCheck.UrlCheckId = urlCheckId;
            urlCheck.UseSsl = useSsl;
            urlCheck.Port = port;
            urlCheck.Name = name;
            urlCheck.RawHttpRequest = rawHttpRequest;
            urlCheck.ExpectedResponse = expectedResponse;
            urlCheck.UnstableThresholdInMilliseconds = unstableThresholdInMilliseconds;
            urlCheck.CriticalThresholdInMilliseconds = criticalThresholdInMilliseconds;
            return urlCheck;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UrlCheckId
        {
            get
            {
                return _UrlCheckId;
            }
            set
            {
                if (_UrlCheckId != value)
                {
                    OnUrlCheckIdChanging(value);
                    ReportPropertyChanging("UrlCheckId");
                    _UrlCheckId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UrlCheckId");
                    OnUrlCheckIdChanged();
                }
            }
        }
        private global::System.Int32 _UrlCheckId;
        partial void OnUrlCheckIdChanging(global::System.Int32 value);
        partial void OnUrlCheckIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean UseSsl
        {
            get
            {
                return _UseSsl;
            }
            set
            {
                OnUseSslChanging(value);
                ReportPropertyChanging("UseSsl");
                _UseSsl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UseSsl");
                OnUseSslChanged();
            }
        }
        private global::System.Boolean _UseSsl;
        partial void OnUseSslChanging(global::System.Boolean value);
        partial void OnUseSslChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Port
        {
            get
            {
                return _Port;
            }
            set
            {
                OnPortChanging(value);
                ReportPropertyChanging("Port");
                _Port = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Port");
                OnPortChanged();
            }
        }
        private global::System.Int32 _Port;
        partial void OnPortChanging(global::System.Int32 value);
        partial void OnPortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RawHttpRequest
        {
            get
            {
                return _RawHttpRequest;
            }
            set
            {
                OnRawHttpRequestChanging(value);
                ReportPropertyChanging("RawHttpRequest");
                _RawHttpRequest = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RawHttpRequest");
                OnRawHttpRequestChanged();
            }
        }
        private global::System.String _RawHttpRequest;
        partial void OnRawHttpRequestChanging(global::System.String value);
        partial void OnRawHttpRequestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ExpectedResponse
        {
            get
            {
                return _ExpectedResponse;
            }
            set
            {
                OnExpectedResponseChanging(value);
                ReportPropertyChanging("ExpectedResponse");
                _ExpectedResponse = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ExpectedResponse");
                OnExpectedResponseChanged();
            }
        }
        private global::System.String _ExpectedResponse;
        partial void OnExpectedResponseChanging(global::System.String value);
        partial void OnExpectedResponseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UnstableThresholdInMilliseconds
        {
            get
            {
                return _UnstableThresholdInMilliseconds;
            }
            set
            {
                OnUnstableThresholdInMillisecondsChanging(value);
                ReportPropertyChanging("UnstableThresholdInMilliseconds");
                _UnstableThresholdInMilliseconds = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnstableThresholdInMilliseconds");
                OnUnstableThresholdInMillisecondsChanged();
            }
        }
        private global::System.Int32 _UnstableThresholdInMilliseconds;
        partial void OnUnstableThresholdInMillisecondsChanging(global::System.Int32 value);
        partial void OnUnstableThresholdInMillisecondsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CriticalThresholdInMilliseconds
        {
            get
            {
                return _CriticalThresholdInMilliseconds;
            }
            set
            {
                OnCriticalThresholdInMillisecondsChanging(value);
                ReportPropertyChanging("CriticalThresholdInMilliseconds");
                _CriticalThresholdInMilliseconds = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CriticalThresholdInMilliseconds");
                OnCriticalThresholdInMillisecondsChanged();
            }
        }
        private global::System.Int32 _CriticalThresholdInMilliseconds;
        partial void OnCriticalThresholdInMillisecondsChanging(global::System.Int32 value);
        partial void OnCriticalThresholdInMillisecondsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Vigilant.Entities", "FK_Receptor_UrlCheck", "Receptor")]
        public EntityCollection<Receptor> Receptors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Receptor>("Vigilant.Entities.FK_Receptor_UrlCheck", "Receptor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Receptor>("Vigilant.Entities.FK_Receptor_UrlCheck", "Receptor", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
